### ISSUE TITLE
window.tinymce ?

### ISSUE THREAD

**Issue by ALPIXELMaiki** [mbouclas/tinymce-vue-2#1]
Hi,

First, thanks for your plugin.

Reading your doc, i don't know what do you mean when you say : "Make sure that window.tinymce is present or it will not work" ?

Can you give a concret exemple of how can i use your pluginwith window.tinymce present ?

Thanks !

**Comment by mbouclas** [comment]
You need to expose tinyMce to window somehow. For example, if you're using webpack, you need to expose it using the expose-loader like so
```
npm install expose-loader --save-dev
```
and in config

```
loaders: [
    { test: require.resolve('tinymce'), loader: 'expose-loader?tinyMCE!expose-loader?$' }
]
```

**Comment by ALPIXELMaiki** [comment]
Thanks for your anwser.

I used now the expose-loader in my webpack2 configuration file :+1: 
```
{
        test: require.resolve('tinymce/tinymce'),
        use: [
            'expose-loader?tinyMCE!expose-loader?$'
        ]
}
```
Here my component (not all the code):
```
<template>
  <tiny-mce
    id="editor"
    v-model="content"
    :toolbar="options"
  >
  </tiny-mce>
</template>

<script>
  import Vue from 'vue'
  import TinyMCE from 'tinymce-vue-2'

  export default {
    data() {
      return {
        ...
        content: '<h2>Title</h2><p>Paragraph</p>',
        options: [
                    'undo redo | styleselect | bold italic | link image',
                    'alignleft aligncenter alignright'
        ]
        ...
      }
    },
    ...
    components: {
      'tiny-mce': TinyMCE
    }
  }
</script>
```

And i have the issue in my console : tinymce is not defined ?

```
[Vue warn]: Error in mounted hook: (found in <TinyMce> at /var/www/node_modules/tinymce-vue-2/TinyMce.vue)
vue.common.js?e881:1449 ReferenceError: tinymce is not defined at VueComponent.mounted (eval at <anonymous> (build.js:2000), <a...
```


Can you see what i'm missing ?

For information, i have a textarea shown (great, the plugin replace the component with this html element), but tinymce is not instanciate.

Thanks :)

**Comment by mbouclas** [comment]
Yeah, it can't find `tinymce`. What i would do is figure out what the exposed variable is in the chrome console (try tinyMCE or window.tinyMCE) and then in my main js file i would try something like window.tinymce = whatEverMyVariableName

**Comment by ALPIXELMaiki** [comment]
Excuse me, i did not understand what you expect to me ? :/

If I try "tinyMCE" in my console, it returns "Uncaught ReferenceError: tinyMCE is not defined at <anonymous>:1:1"
If I try "window.tinyMCE" in my console, it returns 'undefined'

**Comment by onkihara** [comment]
I guess you have to pull in tinymce in in your html-file: <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>

**Comment by samalapsy** [comment]
I had the same issue too...I had to pull tinymce using the CDN
<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
