### ISSUE TITLE
Couldn't find preset "es2015" relative to directory .....

### ISSUE THREAD

**Issue by josephNg95** [mbouclas/tinymce-vue-2#3]
When i import your package: import TinyMCE from 'tinymce-vue-2' to main.js and add it to global component, i'm using Vue.component('tiny-mce', TinyMCE) but CI show me this error: Couldn't find preset "es2015" relative to directory .....

**Comment by mbouclas** [comment]
That's a webpack/babel issue, maybe missing
`babel-preset-es2015`
`babel-preset-stage-2`

A typical config should be 
```
{
    "presets": [
        ["es2015", { "modules": false }]
    ]
}
```

but that's always depending on your project
