### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jasperf** [mbouclas/tinymce-vue-2#4]
What license does this go under? LGPL?

**Comment by mbouclas** [comment]
It's MIT

**Comment by jasperf** [comment]
So a LGPL TinyMCE license wrapped inside an MIT license? The reason I wondered about this as we are working on integrating TinyMCE. Do think you can keep your Vuejs or Laravel app MIT, but TinyMCE should remain LGPL. Perhaps that is what you do here too?

**Comment by mbouclas** [comment]
Yeah, i think you can keep your app as MIT and TinyMCE remains as is (that's the idea anyways)
