### ISSUE TITLE
Error: Couldn't find preset "es2015" relative to directory "E:\\sites\\vuejs-two\\Vue-Helper-Form\\node_modules\\tinymce-vue-2"

### ISSUE THREAD

**Issue by djokone** [mbouclas/tinymce-vue-2#6]
Hi Mbouclas,
Your module looks great, but i have this error below when i import your module
Error: Couldn't find preset "es2015" relative to directory "E:\\sites\\vuejs-two\\Vue-Helper-Form\\node_modules\\tinymce-vue-2"

I'm sure we just have to add this lines to your package.json :
"devDependencies": {
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0"
 }

How we can fix this issue ? 
Many thanks

**Comment by mbouclas** [comment]
Have you installed these presets via npm on your project?

```
babel-preset-es2015
babel-preset-stage-2
```

Try adding a `.babelrc` like so
```
{
    "presets": [
        ["es2015", { "modules": false }]
    ]
}
```

**Comment by djokone** [comment]
Maybe not in this one but if you add to your dev dependencies it work.
I've sent a pull request to your repo ;)
